USE 18fasting;

insert into Classes (title, field, speaker, details, current, max) values("하나님이 설계하신 나의 영성을 찾기!", "그리스도인과 삶", "이정현 간사", " 하나님은 당신을 특정한 성품과 특정한 영적 기질의 소유자로 지으셨다. 9가지 영성기질 테스트를 통해 당신의 영성기질을 알아보고 영혼의 정원을 가꾸자!", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("날마다 큐티 하는 순장", "성경", "김종철 간사", "내 삶을 해석하는 큐티의 실제를 경험하고 캠퍼스 내에 큐티 운동을 일으키는 순장이 되어보자.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("크리스천의 이성교제", "결혼과 가정", "김수진 간사", "세상과 다른 기준인 크리스천의 이성교제에 대해 실제적인 이야기를 나눠보아요.", 0, 30);
insert into Classes (title, field, speaker, details, current, max) values("포스트 모더니즘 속에 사는 내가 만날 19학번", "세계관", "강성철 간사", "한국적 포스트모더니즘의 영향 속에서 있는 19학번들이(그리고 나와 나의 친구들 역시) 어떤 생각과 가치관 속에 있는지 현상을 보고 성경적 대안을 살펴보는 시간.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("스트레스를 부탁해", "그리스도인과 삶", "이나은 간사", "매일매일 생기는 스트레스에 대해 자세히 알아가고, 스트레스를 올바르게 관리하고 정서적, 신체적, 영적으로 자신을 건강하게 가꿀 수 있는 방법을 살펴본다.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("정서적으로 건강한 영성 만들기", "그리스도인과 삶", "정소림 간사", "정서적으로 건강하지 않을 때 어떤 어려움이 생기는지 알아보고, 정서적으로 건강한 영성을 발전시키기 위해 필요한 구체적인 방법을 알아본다.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("일본 기독교 역사와 선교", "선교", "길기진 간사", "오랜 깊이를 갖고 있는 기독교 선교의 역사를 알아보고 어떻게 우리가 일본을 품고 기도하고 선교할 수 있는지에 대해서 나눠보는 시간을 갖는 시간입니다.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("7ways to find the Vision", "진로", "방시리 간사", "비전을 찾아가는 7가지 길잡이.", 0, 30);
insert into Classes (title, field, speaker, details, current, max) values("24‘≠θ", "그리스도인과 삶", "이동수 간사", "대체 하나님의 뜻은 무엇이지? 성경이 말하는 하나님의 뜻을 알아가길 원하는 모든 사람 모여라!", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("U & I", "그리스도인과 삶", "양진웅 간사", "친한 친구,동기인 너와 나 얼마나 맞고 얼마나 안 맞을까? 이고그램을 통해 알아보자!! 친구끼리 같이 모여!!^^", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("종이 위에 기적, 쓰면 이루어진다", "그리스도인과 삶", "성윤제 간사", "2019년 새롭게 시작하는 가운데 목표를 정하고 계획을 세우고 실천하자 그러면 그 행동이 다른 곳에서의 움직임을 이끌어 낼 것이다.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("관계의 골든타임", "그리스도인과 삶", "진인엽 간사", "캠퍼스의 4년! 관계에 고민하는 당신, 관계를 풀지 못하는 이유를 하나님과의 관계에서 찾고 관계의 중요성을 알고 가자!", 0, 30);
insert into Classes (title, field, speaker, details, current, max) values("음란마귀와 맞짱뜨기!", "그리스도인과 삶", "박구연 간사", "그리스도인의 성과 음란물중독에 대해 바로 알고 그리스도인의 거룩함을 회복하자!", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("고구마만 먹고 있는 당신,", "그리스도인과 삶", "이시온 간사", "이제는 사이다 좀 마시자!\n강의내용: 사람들과 지내며 고구마만 먹었던 당신, 이 시간 함께 모여 사이다를 마시며 cool 하게 관계 맺는 법을 나누자.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("주님안에서 믿음의 모험!", "그리스도인과 삶", "김대욱 간사", "일상(Daily) : 일상의 기록 / 삶(Life) : 삶의 나눔 / 프레임(Frame) : 시선과 관점 / 믿음의 모험 (Adventure in faith) : 여행과 모험, 믿음과 도전.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("어서와! 군틴트는 처음이지?", "그리스도인과 삶", "김성도 간사", "군대는 어떤 곳인가? 군입대를 앞둔 형제들에 대한 신앙적 조언과 서로의 생각을 나누는 시간!", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("나를 사랑하게 할 자존감", "상담과 치유", "김윤경 간사", "나를 사랑하지 못하게 하는것 무엇? 나를 사랑할 비결을 알아보아요~", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("선교를 보는 눈 넓히기 - MK(Missionary Kids) 선교", "선교", "강은지 간사", "선교사의 삶의 한 부분. 선교사 자녀를 MK위한 사역. MK가 누구인지 모르는 순장순원 모여라!", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("새생활의 시작 90분 정복하기", "그리스도인과 삶", "엄기윤 간사", "내년부터 순모임을 시작할 예비순장들부터 새생활의 시작으로 순모임하는 것에 어려움을 느끼는 순장들까지 모여 90분동안 새생활의 시작의 핵심을 정리하여 ‘내 것’으로 만듦으로 순모임에 도움을 주려고 합니다.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("Just do something", "그리스도인과 삶", "현주원 간사", "하나님의 뜻에 대한 올바른 관점", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("중보기도는 사랑이다♥︎", "기도", "하예나 간사", "우리 함께 ‘효과적인 중보기도 방법’을 배움으로 하나님께서 사랑하는 지체들을 더욱 사랑해 보아요~^^", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("세계 학생 선교 운동의 역사", "선교", "형동희 간사", "독일 경건주의 운동부터 시작되어 SVM단체를 통해 오늘날 CCC까지 이르는 세계선교의 역사를 배워본다.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("중독과 은혜", "그리스도인과 삶", "정근호 간사", "정도의 차이가 있을 뿐 우리 모두는 무언가의 중독에 빠져 있다. 중독을 이해함으로 하나님의 은혜를 깨닫게 되길 소망해본다.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("말씀으로 하나님과 친밀해지기", "성경", "동성재 간사", "성경 말씀을 통해 단순히 읽는 행위가 아니라, 어떻게 하나님과 친밀해질 수 있는지, 성경을 통한 기도, 변화 등을 다루며 말씀 읽는 것이 더이상 의무가 아니라 기쁨의 시간이 되도록.", 0, 15);
insert into Classes (title, field, speaker, details, current, max) values("귀차니즘 극복하기", "그리스도인과 삶", "도유경 간사", "대학졸업 후에도 무기력에 빠지지 않고, 훈련 받은대로 잘 살아갈 수 있는 방법들을 함께 찾아본다.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("삶에서 영적 도약 경험하기", "그리스도인과 삶", "연규운 목사", "우리의 주위를 주의 깊게 살펴보고 귀를 기울여보라 어느 곳에서나 그것을 느낄 수 있다. 그것은 - 대부분 드러나지는 않지만 - 무엇인가를 바라는 갈망이다. 우리는 지금보다 더 낫고 만족스러운 미래를 꿈꾼다. 이것은 바로 삶의 점프를 갈망하는 것이다. 지금 단계에서 다음 단계로 점프하고 싶은 갈망, 특히 영적으로 한 단계 도약하고 싶은 열망, 그 갈망에서 멈추지 말고 실제로 점프해보자. 그 비결을 찾아가는 경험은 그대를 흥미롭게 할 것이다.", 0, 20);
insert into Classes (title, field, speaker, details, current, max) values("미디어와 세계관", "세계관", "VLM", "그리스도인은 “하나님의 생각을 따라서” 생각하는 사람이다. 즉 나 자신을 비롯하여 이 세상 전체를 성경의 관점으로 바라보는 사람들이라는 말이다.\n\n그런데 오늘 우리가 살펴볼 미디어라고 하는 것이 때로는 우리에게 매우 유익한 정보를 확장시켜 주기도 하지만 죄로 오염된 생각들이 더 널리 퍼지도록 많은 부분에서 기여하기도 한다.\n\n그래서 오늘 우리는 미디어라는 네모난 상자가 어떠한 방식으로 세상을 보여주는지를, 그리고 그것이 우리에게 어떤 영향을 주는지를 생각해보는 시간을 가져보려고 합니다.", 0, 30);

insert into Bible (title, speaker, details, current, max) values("요한계시록과 복음 (이기는 자가 되라)", "이창세 목사", "1) 요한계시록 큰 그림으로 보기.\n2) 요한계시록과 복음(계시록에 나타난 그리스도 / 영적전쟁/ 우리는 어떻게 이길 수 있는가?)\n3)144,000그들은 누구인가(계7,14장)\n4)요한계시록 각장 문제정리", 0, 100);
insert into Bible (title, speaker, details, current, max) values("사사기", "강춘석 목사", "우리는 사사기를 단지 하나의 고대 역사서가 아닌 살아있는 ‘하나님의 말씀’으로 믿고 거기에서 오늘날 우리에게 말씀하시는 하나님의 음성을 듣고자 한다", 0, 100);
insert into Bible (title, speaker, details, current, max) values("기독교 세계관", "현지식 목사", "", 0, 100);
insert into Bible (title, speaker, details, current, max) values("‘성’(sex)에 대한 팩트 체크", "조신형 목사", "섹스, 사랑 그리고 관계에 대한 성경적 진리\n(The Truth about Sex, Love, and Relationship)", 0, 100);
insert into Bible (title, speaker, details, current, max) values("행복하게 잘 지내는 방법\n(1학년만 신청가능)", "장세영 간사", "다양한 활동들과 검사들을 통해나를 알고 너를 알아서 좋은 관계를 맺어가고 유지하는 방법(좋은 관계 형성 프로젝트)", 0, 100);
insert into Bible (title, speaker, details, current, max) values("느헤미야를 통해 본 리더십", "이봉희 간사", "민족의 위기 앞에 철저하게 준비된 실력과 영성으로 외부의 침략과 내부의 분열을 극복하고 이스라엘의 성벽재건을 완성, 영적부흥을 주도한 느헤미야를 통해 배우는 리더십", 0, 100);